(cl:defpackage nomad-srv
  (:use )
  (:export
   "ROBOCLAWDIAGNOSTICS"
   "<ROBOCLAWDIAGNOSTICS-REQUEST>"
   "ROBOCLAWDIAGNOSTICS-REQUEST"
   "<ROBOCLAWDIAGNOSTICS-RESPONSE>"
   "ROBOCLAWDIAGNOSTICS-RESPONSE"
  ))

