// Generated by gencpp from file nomad/RoboclawDiagnosticsRequest.msg
// DO NOT EDIT!


#ifndef NOMAD_MESSAGE_ROBOCLAWDIAGNOSTICSREQUEST_H
#define NOMAD_MESSAGE_ROBOCLAWDIAGNOSTICSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nomad
{
template <class ContainerAllocator>
struct RoboclawDiagnosticsRequest_
{
  typedef RoboclawDiagnosticsRequest_<ContainerAllocator> Type;

  RoboclawDiagnosticsRequest_()
    : input()  {
    }
  RoboclawDiagnosticsRequest_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RoboclawDiagnosticsRequest_

typedef ::nomad::RoboclawDiagnosticsRequest_<std::allocator<void> > RoboclawDiagnosticsRequest;

typedef boost::shared_ptr< ::nomad::RoboclawDiagnosticsRequest > RoboclawDiagnosticsRequestPtr;
typedef boost::shared_ptr< ::nomad::RoboclawDiagnosticsRequest const> RoboclawDiagnosticsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nomad

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39e92f1778057359c64c7b8a7d7b19de";
  }

  static const char* value(const ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39e92f1778057359ULL;
  static const uint64_t static_value2 = 0xc64c7b8a7d7b19deULL;
};

template<class ContainerAllocator>
struct DataType< ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nomad/RoboclawDiagnosticsRequest";
  }

  static const char* value(const ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string input\n\
";
  }

  static const char* value(const ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoboclawDiagnosticsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nomad::RoboclawDiagnosticsRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NOMAD_MESSAGE_ROBOCLAWDIAGNOSTICSREQUEST_H
